### ISSUE TITLE
close of closed channel in peer.(*pex).close(...)

### ISSUE THREAD

**Issue by cenkalti** [cenkalti/rain#99]
```
panic: close of closed channel

goroutine 721 [running]:
github.com/cenkalti/rain/internal/peer.(*pex).close(...)
        /go/pkg/mod/github.com/cenkalti/rain@v1.12.0/internal/peer/pex.go:45
github.com/cenkalti/rain/internal/peer.(*Peer).Close(0xc019c36200)
        /go/pkg/mod/github.com/cenkalti/rain@v1.12.0/internal/peer/peer.go:129 +0x58
github.com/cenkalti/rain/torrent.(*torrent).closePeer(0xc00f215680, 0xc019c36200)
        /go/pkg/mod/github.com/cenkalti/rain@v1.12.0/torrent/torrent_close.go:28 +0x3e
github.com/cenkalti/rain/torrent.(*torrent).handlePieceWriteDone(0xc00f215680, 0xc00eef6780)
        /go/pkg/mod/github.com/cenkalti/rain@v1.12.0/torrent/torrent_write.go:26 +0x528
github.com/cenkalti/rain/torrent.(*torrent).run(0xc00f215680)
        /go/pkg/mod/github.com/cenkalti/rain@v1.12.0/torrent/torrent_run.go:70 +0xd8b
created by github.com/cenkalti/rain/torrent.newTorrent2
        /go/pkg/mod/github.com/cenkalti/rain@v1.12.0/torrent/torrent.go:388 +0x1885
```

**Comment by cenkalti** [comment]
Fixed in 742c1b8135dbe342af79aab2d336329bab64735b
